version: '2'
services:
    php-app:
        build: .
        restart: always
        ports: 
            - "8000:80"        
    db:
        image: mariadb:latest
        container_name: mydatabase
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        ports: 
           - '3307:3306'
        volumes:
            - ./mysql-data:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8181:80
        environment:
             MYSQL_USERNAME: root
             MYSQL_ROOT_PASSWORD: 123456
             PMA_HOST: db
             PMA_PORTS: 3307
